# Change these first
owner: danielpetrica # Your GitHub username
repo: uptime # Your GitHub repository name
user-agent: danielpetrica
# Add your sites here
assignees:
        - danielpetrica
sites:
    - name: Danielpetrica.com
      url: https://danielpetrica.com
    - name: og-image.danielpetrica.com
      url: https://og-image.danielpetrica.com
    #- name: Strapi
     # url: https://strapi.padserver.xyz/
    - name: UnioneUniversitaria.it
      url: https://www.unioneuniversitaria.it
    - name: LoStrilloneUniversitario.it
      url: https://www.lostrilloneuniversitario.it/
    - name: PolifemoFE.it
      url: https://polifemoFe.it/
#   - name: Google
#     url: https://www.google.com
#   - name: Wikipedia
#     url: https://en.wikipedia.org
#   - name: Hacker News
#     url: https://news.ycombinator.com
#   - name: Broken Site
#     url: https://thissitedoesnotexist.com
#   - name: Test for HEAD
#     method: HEAD
#     url: https://www.google.com
#    - name: H24
#      url: $SECRET_SITE_H24
#    - name: Reggio
#      url: $SITE_REGGIO

#   - name: TCP ping
#     url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.danielpetrica.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  theme: night 
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor - Danielpetrica
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime monitor powered by github.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: My site    
      href: https://danielpetrica.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
